dist: xenial
env:
  - COVERALLS_PARALLEL=true
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install pytest pycrypto pytest-cov coveralls
  - pip install -r requirements.txt
  - pip install .
script:
  - pytest --cov-config .coveragerc --cov=ctftools tests
after-success:
  - coveralls
notifications:
  webhooks: https://coveralls.io/webhook
