dist: xenial
env:
  - COVERALLS_PARALLEL=true
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install pytest pycryptodome pytest-cov coveralls
  - pip install -r requirements.txt
  - pip install -r requirements_extra.txt
  - pip install .
script:
  - pytest --cov-config .coveragerc --cov=ctftools tests
after_success:
  - coveralls
notifications:
  webhooks: https://coveralls.io/webhook?repo_token=COVERALLS_REPO_TOKEN
